server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: order_routh  #路由的id,没有固定的规则,但是必须是唯一的
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-pay-service  #通过服务名称匹配的路由地址
          predicates:
            - Path=/order/selectAll  #断言,路径相匹配进行的路由   ====>/order/selectAll/**  注意:此处的Path大写

        - id: order_routh2  #路由的id,没有固定的规则,但是必须是唯一的
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-pay-service  #通过服务名称匹配的路由地址
          predicates:
            - Path=/order/getPort  #断言,路径相匹配进行的路由   ====>/order/getPort/**  注意:此处的Path大写
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用微服务名称进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka